// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "git.garena.com/sea-labs-id/batch-02/aulia-nabil/assignment-05-golang-backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SourceOfFundRepository is an autogenerated mock type for the SourceOfFundRepository type
type SourceOfFundRepository struct {
	mock.Mock
}

// FindById provides a mock function with given fields: id
func (_m *SourceOfFundRepository) FindById(id int) (*model.SourceOfFund, error) {
	ret := _m.Called(id)

	var r0 *model.SourceOfFund
	if rf, ok := ret.Get(0).(func(int) *model.SourceOfFund); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SourceOfFund)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSourceOfFundRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewSourceOfFundRepository creates a new instance of SourceOfFundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSourceOfFundRepository(t mockConstructorTestingTNewSourceOfFundRepository) *SourceOfFundRepository {
	mock := &SourceOfFundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
