// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "git.garena.com/sea-labs-id/batch-02/aulia-nabil/assignment-05-golang-backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// FindByNumber provides a mock function with given fields: number
func (_m *WalletRepository) FindByNumber(number string) (*model.Wallet, error) {
	ret := _m.Called(number)

	var r0 *model.Wallet
	if rf, ok := ret.Get(0).(func(string) *model.Wallet); ok {
		r0 = rf(number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserId provides a mock function with given fields: id
func (_m *WalletRepository) FindByUserId(id int) (*model.Wallet, error) {
	ret := _m.Called(id)

	var r0 *model.Wallet
	if rf, ok := ret.Get(0).(func(int) *model.Wallet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: wallet
func (_m *WalletRepository) Save(wallet *model.Wallet) (*model.Wallet, error) {
	ret := _m.Called(wallet)

	var r0 *model.Wallet
	if rf, ok := ret.Get(0).(func(*model.Wallet) *model.Wallet); ok {
		r0 = rf(wallet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Wallet) error); ok {
		r1 = rf(wallet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: wallet
func (_m *WalletRepository) Update(wallet *model.Wallet) (*model.Wallet, error) {
	ret := _m.Called(wallet)

	var r0 *model.Wallet
	if rf, ok := ret.Get(0).(func(*model.Wallet) *model.Wallet); ok {
		r0 = rf(wallet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Wallet) error); ok {
		r1 = rf(wallet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWalletRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWalletRepository(t mockConstructorTestingTNewWalletRepository) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
